-- megafunction wizard: %Reed Solomon v4.0.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			auk_rs_dec_top_atl
-- ============================================================
-- Generated by Reed Solomon 4.0.0 [Altera, IP Toolbench v1.2.11 build48]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2006 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;
library work;

ENTITY rs_decoder IS
	PORT (
		clk	: IN STD_LOGIC;
		reset	: IN STD_LOGIC;
		rsin	: IN STD_LOGIC_VECTOR (8 DOWNTO 1);
		sink_val	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		source_ena	: IN STD_LOGIC;
		bypass	: IN STD_LOGIC;
		rsout	: OUT STD_LOGIC_VECTOR (8 DOWNTO 1);
		sink_ena	: OUT STD_LOGIC;
		source_val	: OUT STD_LOGIC;
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		decfail	: OUT STD_LOGIC;
		num_err_sym	: OUT STD_LOGIC_VECTOR (5 DOWNTO 1);
		num_err_bit0	: OUT STD_LOGIC_VECTOR (7 DOWNTO 1);
		num_err_bit1	: OUT STD_LOGIC_VECTOR (7 DOWNTO 1)
	);
END rs_decoder;

ARCHITECTURE SYN OF rs_decoder IS

	SIGNAL signal_wire0	:  STD_LOGIC_VECTOR (5 DOWNTO 1);
	SIGNAL signal_wire1	:  STD_LOGIC_VECTOR (8 DOWNTO 1);
	SIGNAL signal_wire2	:  STD_LOGIC;
attribute altera_attribute : string;

--attribute altera_attribute of SYN: ARCHITECTURE is "suppress_da_rule_internal=z100";


	COMPONENT auk_rs_dec_top_atl
	GENERIC (
		m	: NATURAL;
		n	: NATURAL;
		check	: NATURAL;
		genstart	: NATURAL;
		irrpol	: NATURAL;
		rootspace	: NATURAL;
		wide	: NATURAL;
		bitwide	: NATURAL;
		keysize	: STRING;
		Erasures	: STRING;
		Varcheck	: STRING;
		rserr_connect	: STRING;
		err_bit_connect	: STRING;
		inv_file	: STRING
	);
	PORT (
		clk	: IN STD_LOGIC;
		reset	: IN STD_LOGIC;
		rsin	: IN STD_LOGIC_VECTOR (8 DOWNTO 1);
		sink_val	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		source_ena	: IN STD_LOGIC;
		numcheck	: IN STD_LOGIC_VECTOR (5 DOWNTO 1);
		numn	: IN STD_LOGIC_VECTOR (8 DOWNTO 1);
		eras_sym	: IN STD_LOGIC;
		bypass	: IN STD_LOGIC;
		rsout	: OUT STD_LOGIC_VECTOR (8 DOWNTO 1);
		sink_ena	: OUT STD_LOGIC;
		source_val	: OUT STD_LOGIC;
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		decfail	: OUT STD_LOGIC;
		num_err_sym	: OUT STD_LOGIC_VECTOR (5 DOWNTO 1);
		num_err_bit0	: OUT STD_LOGIC_VECTOR (7 DOWNTO 1);
		num_err_bit1	: OUT STD_LOGIC_VECTOR (7 DOWNTO 1)
	);

	END COMPONENT;

BEGIN
	signal_wire0  <= (others => '0');
	signal_wire1  <= (others => '0');
	signal_wire2  <=  '0';

	auk_rs_dec_top_atl_inst : auk_rs_dec_top_atl
	GENERIC MAP (
		m => 8,
		n => 204,
		check => 16,
		genstart => 0,
		irrpol => 285,
		rootspace => 1,
		wide => 5,
		bitwide => 7,
		keysize => "half",
		Erasures => "false",
		Varcheck => "false",
		rserr_connect => "false",
		err_bit_connect => "split_count",
		inv_file => "inv_8_285.hex"
	)
	PORT MAP (
		clk  =>  clk,
		reset  =>  reset,
		rsin  =>  rsin,
		rsout  =>  rsout,
		sink_ena  =>  sink_ena,
		sink_val  =>  sink_val,
		sink_sop  =>  sink_sop,
		sink_eop  =>  sink_eop,
		source_ena  =>  source_ena,
		source_val  =>  source_val,
		source_sop  =>  source_sop,
		source_eop  =>  source_eop,
		numcheck  =>  signal_wire0,
		numn  =>  signal_wire1,
		eras_sym  =>  signal_wire2,
		decfail  =>  decfail,
		bypass  =>  bypass,
		num_err_sym  =>  num_err_sym,
		num_err_bit0  =>  num_err_bit0,
		num_err_bit1  =>  num_err_bit1
	);


END SYN;


-- =========================================================
-- Reed Solomon Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, Reed Solomon Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="Reed-Solomon Compiler"  version="4.0.0"  iptb_version="v1.2.11 build48"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION active_core="auk_rs_dec_top_atl" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_type" value="M512"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "devicefamily" value="Cyclone III"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "Function_core" value="Decoder"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "Erasures" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "Varcheck" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rserr_connect" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "err_bit_connect" value="true"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "full_errbit" value="false"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "test_for" value="BER"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "keysize" value="half"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "m" value="8"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "n" value="204"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "check" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "genstart" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "irrpol" value="285"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rootspace" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "filename" value="rs_decoder.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="AUTO"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone III"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <CONSTANTS>
-- Retrieval info:     <CONSTANT name = "m" value="8"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "n" value="204"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "check" value="16"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "genstart" value="0"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "irrpol" value="285"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "rootspace" value="1"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "wide" value="5"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "bitwide" value="7"  type="INTEGER" />
-- Retrieval info:     <CONSTANT name = "keysize" value="half"  type="STRING" />
-- Retrieval info:     <CONSTANT name = "Erasures" value="false"  type="STRING" />
-- Retrieval info:     <CONSTANT name = "Varcheck" value="false"  type="STRING" />
-- Retrieval info:     <CONSTANT name = "rserr_connect" value="false"  type="STRING" />
-- Retrieval info:     <CONSTANT name = "err_bit_connect" value="split_count"  type="STRING" />
-- Retrieval info:     <CONSTANT name = "inv_file" value="inv_8_285.hex"  type="STRING" />
-- Retrieval info:    </CONSTANTS>
-- Retrieval info:    <PORTS>
-- Retrieval info:     <PORT name = "clk" direction="INPUT"  connect_to="clk"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "reset" direction="INPUT"  connect_to="reset"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "rsin" direction="INPUT"  connect_to="rsin"  default="NODEFVAL"  high_width="8"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "rsout" direction="OUTPUT"  connect_to="rsout"  default="NODEFVAL"  high_width="8"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "sink_ena" direction="OUTPUT"  connect_to="sink_ena"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "sink_val" direction="INPUT"  connect_to="sink_val"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "sink_sop" direction="INPUT"  connect_to="sink_sop"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "sink_eop" direction="INPUT"  connect_to="sink_eop"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "source_ena" direction="INPUT"  connect_to="source_ena"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "source_val" direction="OUTPUT"  connect_to="source_val"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "source_sop" direction="OUTPUT"  connect_to="source_sop"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "source_eop" direction="OUTPUT"  connect_to="source_eop"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "numcheck" direction="INPUT"  connect_to="gnd"  default="NODEFVAL"  high_width="5"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "numn" direction="INPUT"  connect_to="gnd"  default="NODEFVAL"  high_width="8"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "eras_sym" direction="INPUT"  connect_to="gnd"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "decfail" direction="OUTPUT"  connect_to="decfail"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "bypass" direction="INPUT"  connect_to="bypass"  default="NODEFVAL"  width="1"  description="" />
-- Retrieval info:     <PORT name = "num_err_sym" direction="OUTPUT"  connect_to="num_err_sym"  default="NODEFVAL"  high_width="5"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "num_err_bit0" direction="OUTPUT"  connect_to="num_err_bit0"  default="NODEFVAL"  high_width="7"  low_width="1"  description="" />
-- Retrieval info:     <PORT name = "num_err_bit1" direction="OUTPUT"  connect_to="num_err_bit1"  default="NODEFVAL"  high_width="7"  low_width="1"  description="" />
-- Retrieval info:    </PORTS>
-- Retrieval info:    <LIBRARIES>
-- Retrieval info:     <LIBRARY name = "ReedS"/>
-- Retrieval info:    </LIBRARIES>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
-- RELATED_FILES: rs_decoder.vhd;
-- IPFS_FILES: none;
-- =========================================================
